# SOPS configuration for dotfiles secrets management
# This file tells SOPS which files to encrypt and how

creation_rules:
  # Encrypt all files in secrets/ directory
  - path_regex: secrets/.*\.env$
    age: >-
      age18uksntc4lz58z0tkf9vh28m7pazycnwty3dgs0r8p09vg8j8mdwqhhqvau

