#!/bin/bash

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Hide the orphaned commits (using just the hash) - requires git-query
git query 'all() - ancestors(branches())' | cut -d' ' -f1 | while read commit; do
  echo "Hiding orphaned commit: $commit"
  git hide "$commit"
done